spring:
  datasource:
    master:
      username: root
      password: root
      jdbc-url: jdbc:mysql://127.0.0.1:3306/sb_db_master?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver

    slave:
      username: root
      password: root
      jdbc-url: jdbc:mysql://127.0.0.1:3306/sb_db_slave?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: info
  path: ./logs
